---
version: '2'
services:
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=godb
      - POSTGRES_USER=godb
      - POSTGRES_PASSWORD=godb
      - MAX_CONNECTIONS=10

